### ISSUE TITLE
--no-mime-check stops iso label from being added

### ISSUE THREAD

**Issue by Sporif** [jsamr/bootiso#14]
I was using ` --no-mime-check` just to get rid of the warning, but it appears that the iso label isn't applied when you do so. I think this behaviour should be made clear in the usage text or changed so the iso label is always added.

Edit: I see that the next version seems to have has this fixed, so should I'll close this issue once it's released.

**Comment by jsamr** [comment]
@Sporif Thanks for the feedback. I'll check that up in #next branch. Also, `-M` shortcut for `--no-mime-check` in next ;-).
