### ISSUE TITLE
Support Windows 7 32bits and Windows XP images

### ISSUE THREAD

**Issue by jsamr** [jsamr/bootiso#25]
Those OS only work in legacy boot.

There are two paths to explore:

- Install SYSLINUX bootloader and chainload the `bootmgr` file in a second partition.
- Replicate how it is handled by RUFUS: https://superuser.com/a/623998/383691

It will require a lot of investigation, documentation and tests, for an outcome difficult to evaluate.
Thus, I have added a issuehunt entry for this very issue. Please upvote the issue if you are interested.

See: https://issuehunt.io/r/jsamr/bootiso/issues/25

**Comment by HassanMirza01** [comment]
i just added support for it.... just let it go with mbr... remove failandexit variable and use a read command with default "y" option... that way, it will install syslinux mbr compatible and that will work with windows 7 isos... like it should ask if you still wanna proceed at your own risk ?? y/n: y
and if it says yes, just override the failandexit and put it in "n" input ;)

**Comment by HassanMirza01** [comment]
![image](https://user-images.githubusercontent.com/26677817/46610515-6ba47000-cb24-11e8-8802-39dcb99f7f97.png)
