### ISSUE TITLE
Would like to direct the .iso to a boot partition on the flash drive, if at all possible?

### ISSUE THREAD

**Issue by RonCam** [jsamr/bootiso#27]
I have partitioned a 16MiB flash drive into, approximately, two 8MiB partitions, 'boot' (with boot flag set) and 'storage'.  Both are FAT-32, primary partitions, as follows:
```
/dev/sdc1: LABEL="BOOT" UUID="12A2-C2CD" TYPE="vfat"
/dev/sdc2: LABEL="STORAGE" UUID="1379-2FEB" TYPE="vfat"
```
I am attempting to use the -d parameter, but am seeing this:
```
> ./bootiso -d /dev/sdc1 tails-amd64-3.8.iso
bootiso: The selected device `/dev/sdc1' is either unmounted or not a disk (might be a partition or loop).
         Select a disk instead or replug the USB device.
         You can check the availability of USB drives with `bootiso -l' command.
         Exiting...
```

Is there any work-around for this, other than using _dd_ by itself, to get the .iso onto the correct partition?  

**System Information:**
Linux Mint 17.3

**Comment by jsamr** [comment]
@RonCam `bootiso` is not aimed at doing such things.
The reason is that hybrid ISOs are disk images, containing not only one to many partitions, but also partition tables and so on.
However I see you are trying to add a storage partition.
You can easily do this already! I checked the ISO, it will be defaulted to `dd-install` mode in bootiso.
After you have "burned" the USB with `bootiso`, just use your favorite MBR partition wizard (`fdisk`, `parted`) and add a vfat storage partition on the remaining space. Make the filesystem (`mkfs`) and you're good to go :-)

**Comment by RonCam** [comment]
Many thanks for a fast and to-the-point reply.  So, there is a work-around!

If I understand correctly, the procedure is to start off as if you wanted to use the _entire_ flash drive as a boot device, then add the second, third, or whatever number of _vfat_ (or _ext_?) storage partitions, that are wanted.

It's something I'll have to try and see how it goes, because -- and, apparently this may not be the case, because you're saying it can be done -- I thought, when you add a partition to a drive, you have to redo the partition table, which then wipes out anything else that's already on the drive.  I'm just going by my memory of what I recall from the Menu options offered in _gparted_, that I saw while preparing this drive.  

And, you are correct, no, I was not trying to make a multi-boot drive.  Just trying not to waste the extra multiple-GiBs left on the drive.

**Comment by RonCam** [comment]
Ah, now I think I understand.  

It may be done by _resizing_ the existing partition to create the new space, not by _creating_ an additional partition.  OK, that sounds better!

**Comment by HassanMirza01** [comment]
@jsamr i was busy a bit in my professional life, i found the way to your issue no.1 i.e persistent data partition, i wrote the code for it, but i wanna see its versatility so there comes no error in diff iso's and usb's...
