### ISSUE TITLE
Support splitting of install.wim via "wimlib-imagex split" to avoid hitting 4GB file size limit of fat32

### ISSUE THREAD

**Issue by coreprocess** [jsamr/bootiso#32]
https://wimlib.net/ supports splitting of wim files. Exclude `install.wim` from rsync process and copy via the `split` command of `wimlib-imagex` instead.

**Comment by coreprocess** [comment]
@jsamr Please have a look at https://github.com/core-process/wininst-uefi-usb/blob/master/README.md. The instructions are macOS specific, but the copy sequence is identical to the Linux variant.

Most important part is:
```sh
# Copy all files except install.wim
rsync -v -r -I --no-links --no-perms --no-owner --no-group --exclude sources/install.wim /Volumes/WINISO/ /Volumes/WININST/

# Split-copy install.wim
wimlib-imagex split /Volumes/WINISO/sources/install.wim /Volumes/WININST/sources/install.swm 1024
```
On Debian/Ubuntu the `wimlib-imagex` binary can be installed via the https://packages.debian.org/stretch/wimtools package.

**Comment by jsamr** [comment]
@core-process I'm reluctant to add image-specific logic to a bash script ! This is mainly a maintainability concern.

However, I have been thinking of a `go` or `rust` successor to `bootiso` which could have more fine grained logic such as the example you are proposing :slightly_smiling_face:

**Comment by coreprocess** [comment]
@jsamr I understand your concern. But this specific issue is very real and rendered the otherwise very beautiful bootiso script useless to me. :-( The Windows ISO images available at the official download site of Microsoft contain an install.wim file which is larger than 4 GB.

**Comment by jsamr** [comment]
@core-process Oh I didn't catch the motivations at first glance. I will consider this option for next release. I'll ping you when that happens!

**Comment by bboti86** [comment]
@jsamr have you considered using NTFS instead of vfat when the .wim file is too large for FAT? That could be an extra sanity check instead of processing the wim file.

**Comment by coreprocess** [comment]
@bboti86 NTFS is not guaranteed to work, as it is not part of the standard. And I can confirm it does not work in many cases. FAT32 + processing the WIM file does work with any compliant system. (I am talking about UEFI here)

**Comment by jsamr** [comment]
@core-process Currently implementing and testing ; should be shipped with 3.2 soon!

**Comment by NullVoxPopuli** [comment]
Using the master branch, I just tried making a Win10 usb installer. The iso is over 5GB, so, WoeUSB doesn't seem to work for me, becaues of this error: 
![image](https://user-images.githubusercontent.com/199018/52862490-658e5380-3103-11e9-8b7d-52690bf48492.png)

**Comment by NullVoxPopuli** [comment]
however, the CLI works
```bash
sudo woeusb --target-filesystem NTFS --device ~/Downloads/Win10_1809Oct_English_x64.iso /dev/sdf
```

**Comment by jsamr** [comment]
@NullVoxPopuli This is not woeusb ; but bootiso :-) Guess you have been misguided by your favorite search engine.

**Comment by NullVoxPopuli** [comment]
lol. oops

**Comment by paulkinzo** [comment]
I found out wimlib-imagex not working on my Mac with latest Big Sur. The usb is not bootable. A possible solution is to download an old version of Windows 10 (before 2018 release) from [here](https://tb.rg-adguard.net/public.php) and the install.wim file will be less than 4GB so no need to split the image file. 

After that, burn Windows 10 to USB with [UUByte ISO Editor (Mac)](https://www.uubyte.com/iso-editor.html) or [Boot Camp Assistant](https://support.apple.com/en-us/HT201468). This procedure works flawlessly on Mac without splitting the ISO image.
