### ISSUE TITLE
Other format than FAT if files are bigger than 4Gb

### ISSUE THREAD

**Issue by geaplanet** [jsamr/bootiso#45]
It is only a request.
If one file inside ISO is bigger than 4Gb, automatically choose another format for the partition (exfat, ntfs, etc...)

**Comment by jsamr** [comment]
@geaplanet [EFI FAT32 partitions are part of the UEFI standard](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface#EFI_system_partition), so we are not planning to deviate from this.

Can you give me the specific use case / ISO file link ; what you attempted to do ?
