### ISSUE TITLE
Exit in a more controlled way?

### ISSUE THREAD

**Issue by twtonicr** [jsamr/bootiso#51]
**Category** (choose at least one)

- *behavior* 

**Describe the bug**
Feature request?

When certain pre-requisites aren't met, the script exists fine. But the messages giving reasons are invisible unless run from a terminal.

E.g. I have a nautilus action set up so I can right-click a .iso file.  I'm prompted for sudo password OK, but if things aren't correct, e.g. If there is no USB inserted, the window closes immediately with no info.

I cludged a workaround by adding a sleep to the message function:
```
# $1: The message to print.
failAndExit() {
	echoerr "$@" "Exiting..."
	sleep 10  # Added to keep exit reasons visible
	exit 1
}
```

**For ref: Setting up action**

in Nautilus-actions / fma-config-tool

path:  /usr/bin/gnome-terminal
Parameters: --working-directory=%d --command="/path_to_script/bootiso %f"

**Comment by jsamr** [comment]
@abssorb I think what you're asking is out of scope of bootiso. You could create your own script which `sleep 10` when `bootiso` return status is not 0.
