### ISSUE TITLE
Feature Request: appimage

### ISSUE THREAD

**Issue by tgharib** [jsamr/bootiso#56]
I tried to use `bootiso` on openSUSE tumbleweed. However, I was unable to use it because of a missing dependency on `wimlib`. `wimlib-devel` exists in the tumbleweed repos but not `wimlib` and `wimlib-devel` was not enough for `bootiso` to run.

Therefore, I propose an appimage distribution method.

**Comment by jsamr** [comment]
@tgharib I would rather open a ticket in openSUSE maintainers if I were you; I don't have the bandwidth to offer other distribution methods.

**Comment by jsamr** [comment]
@tgharib It is referenced in openSUSE official repositories: https://software.opensuse.org/package/wimlib

Perhaps you had an outdated tumbleweed?
